/*
export const ACCOUNT = {
    SAVE: 'SAVE',
    CANCEL: 'CANCEL',
    ADD_ACCOUNT: 'ADD_ACCOUNT',
    ADD_ROW: 'ADD_ROW',
    UPDATE_ROW: 'UPDATE_ROW',
    SELECT_ACCT_TYPE: 'SELECT_ACCT_TYPE'
}
*/

export const ACCOUNTS = {
    LOAD: 'LOAD',
    SAVE: 'SAVE',
    CANCEL: 'CANCEL',
    ADD_ACCOUNT: 'ADD_ACCOUNT',
    ADD_ROW: 'ADD_ROW',
    UPDATE_ROW: 'UPDATE_ROW',
    SELECT_ACCT_TYPE: 'SELECT_ACCT_TYPE'
}