export const ACCOUNTS = {
    LOAD: 'LOAD',
    SAVE: 'SAVE',
    CANCEL: 'CANCEL',
    ADD_ACCOUNT: 'ADD_ACCOUNT',
    ADD_ROW: 'ADD_ROW',
    UPDATE_ROW: 'UPDATE_ROW',
    SELECT_ACCT_TYPE: 'SELECT_ACCT_TYPE',
    SET_PORTFOLIO_NAME: 'SET_PORTFOLIO_NAME'
}